#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Regenerate original Ogg test tones using the host's ffmpeg/libvorbis.

Run manually after a deliberate fixture update. Tests use the checked-in bytes
and need no ffmpeg. Encoder/container versions may alter those bytes.
"""
import math
from pathlib import Path
import struct
import subprocess
import tempfile
import wave

ROOT = Path(__file__).resolve().parents[1]
fixtures = []
with tempfile.TemporaryDirectory(prefix="kui-vorbis-") as temp:
    for name, rate, channels in (("mono", 22050, 1), ("stereo", 44100, 2)):
        wav_path = Path(temp) / f"{name}.wav"
        with wave.open(str(wav_path), "wb") as output:
            output.setparams((channels, 2, rate, 0, "NONE", "not compressed"))
            for frame in range(rate // 2):
                output.writeframesraw(b"".join(
                    struct.pack("<h", int(10000 * math.sin(2 * math.pi * (440 + 110 * channel) * frame / rate)))
                    for channel in range(channels)))
        ogg_path = wav_path.with_suffix(".ogg")
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", str(wav_path),
                        "-c:a", "libvorbis", "-q:a", "2", str(ogg_path)], check=True)
        fixtures.append((name, ogg_path.read_bytes()))
header = ("/* SPDX-License-Identifier: GPL-3.0-only */\n"
          "/* Original synthetic 0.5-second 440/550 Hz test tones; encoded by FFmpeg libvorbis.\n"
          " * Samples generated by tests/make_music_vorbis.py; no third-party audio. */\n")
for name, data in fixtures:
    header += f"static const unsigned char ogg_{name}[] = {{\n"
    for at in range(0, len(data), 16):
        header += "    " + ",".join(f"0x{byte:02x}" for byte in data[at:at+16]) + ",\n"
    header += "};\n"
(ROOT / "tests/fixtures/music_vorbis.h").write_text(header)
