#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate the committed, dependency-free shell font atlas from bundled TTFs.

Normal console builds compile shell_font_data.inc and do not run this script.
For byte-identical regeneration use Pillow 12.3.0 with FreeType 2.14.3.
"""
from pathlib import Path
import argparse
import hashlib
import math

from PIL import Image, ImageDraw, ImageFont, features

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/dreamcast/shell_font_data.inc"
FONTS = (
    ("small", "DejaVuSans.ttf", 14, 18, "ae7b7855e115a5966d8b1b3f80f254ccc117ec86f9965e202ee2940453837280"),
    ("large", "DejaVuSans-Bold.ttf", 20, 24, "5c1247acef7f2b8522a31742c76d6adcb5569bacc0be7ceaa4dc39dd252ce895"),
)


def build_font(name, filename, size, line_height, digest):
    path = ROOT / "resources/fonts" / filename
    if hashlib.sha256(path.read_bytes()).hexdigest() != digest:
        raise ValueError(f"{path}: source font checksum differs from the recorded original")
    font = ImageFont.truetype(str(path), size, layout_engine=ImageFont.Layout.BASIC)
    metrics, pixels = [], []
    for code in range(32, 127):
        char = chr(code)
        left, top, right, bottom = font.getbbox(char, anchor="la")
        width, height = right - left, bottom - top
        # Each cell holds its whole glyph. Negative left bearings (J/j/T/Y)
        # become zero so adjacent labels never paint outside measured width.
        bearing = max(0, left)
        advance = max(math.ceil(font.getlength(char)), bearing + width)
        if width and height:
            glyph = Image.new("L", (width, height))
            ImageDraw.Draw(glyph).text((-left, -top), char, font=font, fill=255, anchor="la")
            values = [(value + 8) // 17 for value in glyph.tobytes()]
            # Include any positive bearing as transparent pixels in each row.
            width += bearing
            stride = (width + 1) // 2
            offset = len(pixels)
            for y in range(height):
                row = [0] * bearing + values[y * (right - left):(y + 1) * (right - left)]
                if len(row) & 1:
                    row.append(0)
                pixels.extend((row[x] << 4) | row[x + 1] for x in range(0, len(row), 2))
        else:
            width = height = stride = 0
            offset = len(pixels)
        assert 0 <= top <= top + height <= line_height
        assert width <= advance < 256 and offset <= 65535
        metrics.append((offset, width, height, stride, advance, top))
    lines = [f"/* {filename}, {size}px, SHA-256 {digest} */", f"static const struct glyph {name}_glyphs[95] = {{"]
    for code, values in zip(range(32, 127), metrics):
        lines.append("    {" + ",".join(map(str, values)) + f"}}, /* ASCII {code} */")
    lines += ["};", f"static const uint8_t {name}_pixels[{len(pixels)}] = {{"]
    for at in range(0, len(pixels), 20):
        lines.append("    " + ",".join(f"0x{value:02x}" for value in pixels[at:at + 20]) + ",")
    lines += ["};", ""]
    return "\n".join(lines)


def generate():
    if Image.__version__ != "12.3.0" or features.version_module("freetype2") != "2.14.3":
        raise RuntimeError("Exact regeneration requires Pillow 12.3.0 / FreeType 2.14.3; normal builds need neither")
    header = (
        "/* Generated by tools/generate_shell_font.py; do not edit.\n"
        " * ASCII 32..126, 4-bit coverage, high nibble first; 1px spacing is in the renderer.\n"
        " * Rasterizer: Pillow 12.3.0 / FreeType 2.14.3, BASIC layout, no kerning.\n"
        " * Font-derived data: DejaVu/Bitstream Vera license, LICENSES/DejaVu-fonts.txt.\n"
        " * Copyright (c) 2003 by Bitstream, Inc. All Rights Reserved.\n"
        " * Bitstream Vera is a trademark of Bitstream, Inc. DejaVu changes are public domain.\n"
        " */\n\n"
    )
    return header + "\n".join(build_font(*font) for font in FONTS)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="compare with the committed atlas without changing it")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if OUTPUT.read_text() != generated:
            raise SystemExit("Shell font atlas is out of date; regenerate with tools/generate_shell_font.py")
        print("PASS shell font atlas: reproducible from bundled fonts")
    else:
        OUTPUT.write_text(generated)
        print(f"Generated {OUTPUT.relative_to(ROOT)} ({len(generated)} source bytes)")


if __name__ == "__main__":
    main()
