#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Encode the approved original launcher artwork as fixed RGB565 arrays.

Requires Pillow only. The unmodified SVG sources and their original rendered
PNGs remain in resources/icons. Use --check to verify the committed output;
ordinary Dreamcast builds consume that output without Python image dependencies.
"""
from pathlib import Path
import argparse
import hashlib
import sys

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/dreamcast/shell_art.inc"
TRANSPARENT = 0xF81F
SOURCES = {
    "resources/branding/launcher-brand.png": "a5d98f17ae66cc549760e98a7907a2c680d4af0d57ea209bab07df7cb7e50355",
    "resources/icons/disc-ripper.svg": "8263c8ef8efe9b779863303f90d921f90b9374c734255cb8f119463990eaa683",
    "resources/icons/disc-ripper.png": "1c3bb0ed7ffc95949a06339b16b87f8392de6ed443cd92e4913a4b8d70c1283b",
    "resources/icons/settings.svg": "772f5912638c1e0996edd51be50ec2c2d5c9bd6c4761f76b892da5a60cf13ccd",
    "resources/icons/settings.png": "7d5577f04247961016fd04ab620ebef998ae14982967372af8a766b1bf61f74b",
    "resources/icons/diagnostics.svg": "b23ed82505824f2c43ba3b05262533d27d358cc68ceeaf9496c61708e7ab662d",
    "resources/icons/diagnostics.png": "8b1119e261aa24b8ac5aaef898f736f738fdee9efcb2a1f4622193682097b863",
}
ICONS = ("disc-ripper", "settings", "diagnostics")


def pixels(path, dimensions, background, transparent=False):
    with Image.open(ROOT / path) as source:
        expected = (256, 128) if "launcher-brand" in path else (64, 64)
        if source.size != expected:
            raise ValueError(f"Unexpected source dimensions: {path}: {source.size}")
        # Bilinear filtering follows the original launcher's scaled textures.
        rgba = source.convert("RGBA").resize(dimensions, Image.Resampling.BILINEAR)
    combined = Image.new("RGBA", dimensions, background)
    combined.alpha_composite(rgba)
    out = []
    packed = combined.tobytes()
    for i, alpha in enumerate(rgba.getchannel("A").tobytes()):
        r, g, b = packed[i * 4:i * 4 + 3]
        value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        if transparent and alpha == 0:
            value = TRANSPARENT
        elif transparent and value == TRANSPARENT:
            raise ValueError(f"Opaque pixel collides with the transparency key: {path}")
        out.append(value)
    assert len(out) == dimensions[0] * dimensions[1]
    return out


def rows(values):
    return "\n".join("    " + ",".join(f"0x{x:04x}" for x in values[i:i + 16]) + ","
                     for i in range(0, len(values), 16))


def generate():
    for path, expected in SOURCES.items():
        if hashlib.sha256((ROOT / path).read_bytes()).hexdigest() != expected:
            raise ValueError(f"Original source hash differs: {path}")
    text = ["/* SPDX-License-Identifier: GPL-3.0-only */",
            "/* Generated by tools/generate_shell_art.py; do not edit pixels by hand.",
            " * Original TPMJB K-UI artwork: resources/branding/README.md.",
            " * Icons use 0xf81f for fully transparent pixels; skip those on draw.",
            " * Antialiased icon edges are precomposed against panel #121A31. */",
            "#ifndef KUI_SHELL_ART_INC", "#define KUI_SHELL_ART_INC", "#include <stdint.h>",
            "#define KUI_ART_TRANSPARENT 0xf81fu",
            "#define KUI_ART_BRAND_WIDTH 128u", "#define KUI_ART_BRAND_HEIGHT 64u",
            "#define KUI_ART_ICON_WIDTH 128u", "#define KUI_ART_ICON_HEIGHT 128u",
            "#define KUI_ART_SMALL_ICON_WIDTH 24u", "#define KUI_ART_SMALL_ICON_HEIGHT 24u",
            "#define KUI_ART_ICON_COUNT 3u", "",
            "static const uint16_t kui_art_brand[128 * 64] = {",
            rows(pixels("resources/branding/launcher-brand.png", (128, 64), "#080F23")), "};", ""]
    for symbol, side in (("kui_art_icons", 128), ("kui_art_small_icons", 24)):
        text.append(f"static const uint16_t {symbol}[3][{side} * {side}] = {{")
        for name in ICONS:
            text.extend([f"  {{ /* {name} */", rows(pixels(f"resources/icons/{name}.png",
                         (side, side), "#121A31", transparent=True)), "  },"])
        text.extend(["};", ""])
    text.append("#endif")
    return "\n".join(text) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without rewriting")
    args = parser.parse_args()
    try:
        content = generate()
        if args.check:
            if not OUTPUT.exists() or OUTPUT.read_text() != content:
                print("Shell art is stale; run tools/generate_shell_art.py", file=sys.stderr)
                return 1
            print("Shell art matches the pinned original source assets.")
        else:
            OUTPUT.write_text(content)
            print(f"Wrote {OUTPUT.relative_to(ROOT)} (118144 bytes of RGB565 pixels)")
        return 0
    except (OSError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
